#!/bin/bash
clear
echo "starting tools... /";
sleep 0.1;
clear
echo 'Starting tools... -';
sleep 0.1;
clear
echo 'sTarting tools... \';
sleep 0.1;
clear
echo "stArting tools... /";
sleep 0.1;
clear
echo 'staRting tools... -';
sleep 0.1;
clear
echo 'starTing tools... \';
sleep 0.1;
clear
echo "startIng tools... /";
sleep 0.1;
clear
echo "startiNg tools... -";
sleep 0.1;
clear
echo 'startinG tools... \';
sleep 0.1;
clear
echo 'starting Tools... -';
sleep 0.1;
clear
echo "starting tOols... /";
sleep 0.1;
clear
echo 'starting toOls... -';
sleep 0.1;
clear
echo 'starting tooLs... \';
sleep 0.1;
clear
echo "starting toolS... /";
sleep 0.1;
clear
echo "starting tools... /";
sleep 0.1;
clear
echo 'Starting tools... -';
sleep 0.1;
clear
echo 'sTarting tools... \';
sleep 0.1;
clear
echo "stArting tools... /";
sleep 0.1;
clear
echo 'staRting tools... -';
sleep 0.1;
clear
echo 'starTing tools... \';
sleep 0.1;
clear
echo "startIng tools... /";
sleep 0.1;
clear
echo "startiNg tools... -";
sleep 0.1;
clear
echo 'startinG tools... \';
sleep 0.1;
clear
echo 'starting Tools... -';
sleep 0.1;
clear
echo "starting tOols... /";
sleep 0.1;
clear
echo 'starting toOls... -';
sleep 0.1;
clear
echo 'starting tooLs... \';
sleep 0.1;
clear
echo "starting toolS... /";
sleep 0.1;
clear
echo "starting tools... /";
sleep 0.1;
clear
echo 'Starting tools... -';
sleep 0.1;
clear
echo 'sTarting tools... \';
sleep 0.1;
clear
echo "stArting tools... /";
sleep 0.1;
clear
echo 'staRting tools... -';
sleep 0.1;
clear
echo 'starTing tools... \';
sleep 0.1;
clear
echo "startIng tools... /";
sleep 0.1;
clear
echo "startiNg tools... -";
sleep 0.1;
clear
echo 'startinG tools... \';
sleep 0.1;
clear
echo 'starting Tools... -';
sleep 0.1;
clear
echo "starting tOols... /";
sleep 0.1;
clear
echo 'starting toOls... -';
sleep 0.1;
clear
echo 'starting tooLs... \';
sleep 0.1;
clear
echo "starting toolS... /";
sleep 0.1;
clear
echo "starting tools... /";
sleep 0.1;
clear
echo 'Starting tools... -';
sleep 0.1;
clear
echo 'sTarting tools... \';
sleep 0.1;
clear
echo "stArting tools... /";
sleep 0.1;
clear
echo 'staRting tools... -';
sleep 0.1;
clear
echo 'starTing tools... \';
sleep 0.1;
clear
echo "startIng tools... /";
sleep 0.1;
clear
echo "startiNg tools... -";
sleep 0.1;
clear
echo 'startinG tools... \';
sleep 0.1;
clear
echo 'starting Tools... -';
sleep 0.1;
clear
echo "starting tOols... /";
sleep 0.1;
clear
echo 'starting toOls... -';
sleep 0.1;
clear
echo 'starting tooLs... \';
sleep 0.1;
clear
echo "starting toolS... /";
sleep 0.1;
clear
echo "starting tools... /";
sleep 0.1;
clear
echo 'Starting tools... -';
sleep 0.1;
clear
echo 'sTarting tools... \';
sleep 0.1;
clear
echo "stArting tools... /";
sleep 0.1;
clear
echo 'staRting tools... -';
sleep 0.1;
clear
echo 'starTing tools... \';
sleep 0.1;
clear
echo "startIng tools... /";
sleep 0.1;
clear
echo "startiNg tools... -";
sleep 0.1;
clear
echo 'startinG tools... \';
sleep 0.1;
clear
echo 'starting Tools... -';
sleep 0.1;
clear
echo "starting tOols... /";
sleep 0.1;
clear
echo 'starting toOls... -';
sleep 0.1;
clear
echo 'starting tooLs... \';
sleep 0.1;
clear
echo "starting toolS... /";
sleep 0.1;
clear
echo "starting tools... /";
sleep 0.1;
clear
echo 'Starting tools... -';
sleep 0.1;
clear
echo 'sTarting tools... \';
sleep 0.1;
clear
echo "stArting tools... /";
sleep 0.1;
clear
echo 'staRting tools... -';
sleep 0.1;
clear
echo 'starTing tools... \';
sleep 0.1;
clear
echo "startIng tools... /";
sleep 0.1;
clear
echo "startiNg tools... -";
sleep 0.1;
clear
echo 'startinG tools... \';
sleep 0.1;
clear
echo 'starting Tools... -';
sleep 0.1;
clear
echo "starting tOols... /";
sleep 0.1;
clear
echo 'starting toOls... -';
sleep 0.1;
clear
echo 'starting tooLs... \';
sleep 0.1;
clear
echo "starting toolS... /";
sleep 0.1;
clear

reset

echo "[#...................]5%";
sleep 0.2;
clear
echo "[##..................]10%";
sleep 0.1;
clear
echo "[###.................]15%";
sleep 0.1;
clear
echo "[####................]20%";
sleep 0.1;
clear
echo "[#####...............]25%";
sleep 0.1;
clear
echo "[######..............]30%";
sleep 0.1;
clear
echo "[#######.............]35%";
sleep 0.1;
clear
echo "[########............]40%";
sleep 0.1;
clear
echo "[#########...........]45%";
sleep 0.1;
clear
echo "[##########..........]50%";
sleep 0.1;
clear
echo "[###########.........]55%";
sleep 0.1;
clear
echo "[############........]60%";
sleep 0.1;
clear
echo "[#############.......]65%";
sleep 0.1;
clear
echo "[##############......]70%";
sleep 0.1;
clear
echo "[###############.....]75%";
sleep 0.1;
clear
echo "[################....]80%";
sleep 0.1;
clear
echo "[#################...]85%";
sleep 0.1;
clear
echo "[##################..]90%";
sleep 0.1;
clear
echo "[###################.]95%";
sleep 0.1;
clear
echo "[####################]100%";
sleep 0.3;
clear

echo "starting..."
     sleep 0.7
clear

echo "\033[32m ===================== Welcome ===================";
echo '         [+] Coded : Tn.Herp                           ';
echo '         [+] Id Fb : Gwimusa3                          ';
echo '         [+] IG    : @Rezadkim                         ';
echo '         [+] WA    : 0895611252563 & 089620134992      ';
echo '         ------------------ FaceBook Tools ---------------';
echo '';
sleep 0.7
clear

reset

echo "   .___         .        .  ";
echo '   [__  _. _. _ |_  _  _ ;_/';
echo '   |   (_](_.(/,[_)(_)(_)| \';
echo '';
echo 'Msg: Njeng :V!';
echo '';
echo 'Pilih Opsi:';
echo '[1] - fbbrute (bruteforce)';
echo '[2] - Fbook (bruteforce)';
echo '[3] - MBF';
echo '[4] - Bot fb By BangDjon';
echo '[5] - auto report FB';

echo ''
read -p "fake@tools:~#" command
if [ $command -eq 1 ];
	then
		cd data/ && chmod +x fb.py && python2 fb.py
elif [ $command -eq 2 ];
	then
		cd data/ && chmod +x fbook.py && python2 fbook.py

elif [ $command -eq 3 ];
        then
                cd data/ && chmod +x MBF.py && python2 MBF.py

elif [ $command -eq 4 ];
        then
                cd data/ && chmod +x bangdjon.py && python2 bangdjon.py

elif [ $command -eq 5 ];
        then
                cd data/ && chmod +x autoreport-fb.rb && ruby autoreport-fb.rb


fi